### ISSUE TITLE
win32 compilation error

### ISSUE THREAD

**Issue by re-polm** [roboticeyes/openrex#43]
Introduced in df73

Reproduce compiling just the `openrex` target on win32. You _need_ to clean the solution before compiling the previous commit 01de otherwise the error continues to appear although in a clean solution does not.

`
Error	D8021	invalid numeric argument '/Wno-format-truncation'	openrex	C:\Users\polmo\code\openrex\build\src\cl	1	
`

**Comment by breiting** [comment]
It seems that this flag is not available for the Win32 compiler
