### ISSUE TITLE
rex-info: Material Should Also Show TextureID

### ISSUE THREAD

**Issue by re-ckart** [roboticeyes/openrex#48]
The rex-info tool does not show the `texture id` if a texture is set in the material. This would make debugging exporter implementations easier.

**Comment by breiting** [comment]
What exactly do you mean? the rex-info in master should show it correctly, here an example. The `textureId` is the last column of the color entry.

```
═══════════════════════════════════════════
id                                      102
type                       MaterialStandard
version                                   1
sz                                       68
Ka                   0.00  0.00  0.00    -1
Kd                   1.00  1.00  1.00   103
Ks                   0.00  0.00  0.00    -1
ns                                    64.00
alpha                                  1.00
```

**Comment by breiting** [comment]
```
Ka                   0.00  0.00  0.00    -1
```

Each color entry is RGB+TextureID, so in this example, no texture is set for ambient color
